dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.2.2

compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.2"
dotenv: .env
networks:
  bsc-test:
    eth_usd_price_feed: "0x143db3CEEfbdfe5631aDD3E50f7614B6ba708BA7"
    verify: True

wallets:
  from_key: ${PRIVATE_KEY}
